// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdouKLHhOJkYlt8qqS9FkrI-mOYaQLc_I',
    appId: '1:531672485260:web:7d2838558e761ef593daa9',
    messagingSenderId: '531672485260',
    projectId: 'finance-companion-3d4fa',
    authDomain: 'finance-companion-3d4fa.firebaseapp.com',
    storageBucket: 'finance-companion-3d4fa.firebasestorage.app',
    measurementId: 'G-HBXKY8M4LY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2kJW_o66zbB-kTaq3PCJIjAVvEI2Ln3A',
    appId: '1:531672485260:android:451084416c39a5d393daa9',
    messagingSenderId: '531672485260',
    projectId: 'finance-companion-3d4fa',
    storageBucket: 'finance-companion-3d4fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLJGDu7wVMwtB9T1e_vWFDmOaRIY2mLxQ',
    appId: '1:531672485260:ios:1a51d6efc2f66d1a93daa9',
    messagingSenderId: '531672485260',
    projectId: 'finance-companion-3d4fa',
    storageBucket: 'finance-companion-3d4fa.firebasestorage.app',
    iosBundleId: 'com.example.financeCompanion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLJGDu7wVMwtB9T1e_vWFDmOaRIY2mLxQ',
    appId: '1:531672485260:ios:1a51d6efc2f66d1a93daa9',
    messagingSenderId: '531672485260',
    projectId: 'finance-companion-3d4fa',
    storageBucket: 'finance-companion-3d4fa.firebasestorage.app',
    iosBundleId: 'com.example.financeCompanion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdouKLHhOJkYlt8qqS9FkrI-mOYaQLc_I',
    appId: '1:531672485260:web:b023fa02edd3abb393daa9',
    messagingSenderId: '531672485260',
    projectId: 'finance-companion-3d4fa',
    authDomain: 'finance-companion-3d4fa.firebaseapp.com',
    storageBucket: 'finance-companion-3d4fa.firebasestorage.app',
    measurementId: 'G-MQXFDZ7HGP',
  );
}
